### ISSUE TITLE
[Suggestions]little hermit crab drop shell piece

### ISSUE THREAD

**Issue by KanaTomokawa** [sv3r/CuteHermitCrabs#1]
When little hermit crab was grow up，they drop a shell piece like vanilla‘s turtle

**Comment by sv3r** [comment]
Hi, thanks for the suggestion! Hermit crabs don't have shells when they are born so it wouldn't make sense to drop a shell piece when they grow up.

**Comment by KanaTomokawa** [comment]
> Hi, thanks for the suggestion! Hermit crabs don't have shells when they are born so it wouldn't make sense to drop a shell piece when they grow up.

Thanks, but I think we need to add a way to get the shell piece without killing the hermit crab, they so cute.

**Comment by sv3r** [comment]
Well, unfortunately that's the sacrifice you have to make to get it. Although I might add an other way to obtain it that doesn't contain killing.

**Comment by KanaTomokawa** [comment]
> Well, unfortunately that's the sacrifice you have to make to get it. Although I might add an other way to obtain it that doesn't contain killing.

Okay, I hope so.
