### ISSUE TITLE
[feature request] add config for resistance level given

### ISSUE THREAD

**Issue by EnderMelody** [sv3r/CuteHermitCrabs#3]
could you add a config that allows us to set the resistance level given to the player when using the helmet?

**Comment by sv3r** [comment]
Thanks for the suggestion! This is now added in the following versions:
- [1.18.2](https://www.curseforge.com/minecraft/mc-mods/cute-hermit-crabs/files/3943591)
- [1.19-1.19.2](https://www.curseforge.com/minecraft/mc-mods/cute-hermit-crabs/files/3943599)
