### ISSUE TITLE
[BUG]: Crabs missing English text translation

### ISSUE THREAD

**Issue by AngleWyrm10** [sv3r/CuteHermitCrabs#4]
### Mod Version

1.18.2-2.0.1

### Forge Version

40.1.73

### What happened?

![2022-08-30_19 50 03](https://user-images.githubusercontent.com/55937426/187582079-f8159961-25bd-4d8f-8f52-4709da881f1a.png)

### latest.log

[latest.log](https://github.com/Sv3r/CuteHermitCrabs/files/9457931/latest.log)

**Comment by sv3r** [comment]
This is already fixed in the following versions.
- [1.18.2](https://www.curseforge.com/minecraft/mc-mods/cute-hermit-crabs/files/3943591)
- [1.19-1.19.2](https://www.curseforge.com/minecraft/mc-mods/cute-hermit-crabs/files/3943599)
